name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: SonarScanner for .NET 8 with p ull request decoration support
        uses: highbyte/sonarscan-dotnet@v2.3.1
        with:
          # The key of the SonarQube project
          sonarProjectKey: dotlogic-trial_cshar
          # The name of the SonarQube project
          sonarProjectName:  csharp
          # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
          sonarOrganization: dotlogic-trial
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        